# configurações de documentação da api
springdoc:
    api-docs.path: /swagger-ui/api-docs
    swagger-ui.path: /swagger-ui.html
    swagger-ui.operationsSorter: method  

spring: 
    # configurações de acesso ao banco de dados
    datasource:
        url: jdbc:mysql://localhost:3306/alfa_hackathon?useSSL=false
        username: ALFA_BACKEND
        password: HbC-AN@sB_Em.Bpn
        driver-class-name: com.mysql.cj.jdbc.Driver
    # configurações da ORM de acesso aos dados
    jpa:
        hibernate:
            ddl-auto: update #update quando mais avançado no sistema
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                format-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
    # configurações de horarios e datas
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss.SSS"
        time-zone: "GMT+8"
        
server:
    # Porta de execução do backend
    port: 8030
    #ssl.key-store: keystore.p12
    #ssl.key-store-password: ELFssl73556081597534682Alpha*.*
    #ssl.keyStoreType: PKCS12
    #ssl.keyAlias: ElfCertificate

elf:
    # configurações para geração de chaves e constantes
    default-page-size: 10
    jwt-secret-token: 1c70aee2309ddb582b564cc23e1af437a769b471fc7dd307d1fbea3b39101e0d